Vue CLIを使って、SPAなメモアプリを作成しました。
naomichi-h/memoApp-Vue-CLI pull request #1
Opened 2021-10-31 11:43 UTC by naomichi-h

状態管理にVuexを使用しています。
レビューのほど、よろしくお願いいたします。

2021-11-04 05:21 UTC, komagata requested changes

2021-11-04 05:21 UTC, komagata commented on src/components/createMemo.vue
> +
不要な空行があるみたいです〜

2021-11-04 05:21 UTC, komagata commented on src/components/createMemo.vue
> +      this.$store.commit('editFlgOn')
> Flg

あまり略さない方がいいかもです〜

[プログラミング初心者は変数名やメソッド名を略さない方がいいよ、という話 - give IT a try](https://blog.jnito.com/entry/2020/10/20/092724)

またフラグという単語は意味が広すぎるのでなるべく使わずに表現できた方がわかりやすいと思います。

2021-11-04 05:21 UTC, komagata commented on src/components/indexMemo.vue
> +      {{ memo.text.split(/\r\n|\r|\n/)[0] }}
算出プロパティを使った方がいいかもです。

[算出プロパティとウォッチャ — Vue.js](https://jp.vuejs.org/v2/guide/computed.html#%E7%AE%97%E5%87%BA%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3)

2021-11-04 09:26 UTC, naomichi-h commented
レビューありがとうございます😄
コメントいただいた箇所の修正を行いましたので、確認のほどよろしくお願いいたします🙇‍♂️

2021-11-09 15:17 UTC, komagata requested changes

2021-11-09 15:17 UTC, komagata commented on .gitignore
> +
不要な空行があるようです〜

2021-11-09 15:17 UTC, komagata commented on src/App.vue
> +<style>
style要素が二つあるようです。
scopedでないstyleが必要であればcssファイルに書くのが良いと思います。

2021-11-09 15:17 UTC, komagata commented on src/components/header.vue
> +    <h1 class="app-title">memo app</h1>
indentの数が他と違うようです〜。

2021-11-10 00:22 UTC, naomichi-h commented
レビューありがとうございます😄
コメントいただいた箇所の修正を行いましたので、確認のほどよろしくお願いいたします🙇‍♂️

2021-11-10 13:38 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-11-12 11:46 UTC, merged